### ISSUE TITLE
SNPhood package displaying improperly on website

### ISSUE THREAD

**Issue by b-long** [Bioconductor/bioconductor.org_archive#1]
Val & Martin reported issue with the SNPhood package  :

> The vignette titles for the SNPhood package aren't displaying correctly
> on the landing page:
> http://www.bioconductor.org/packages/3.3/bioc/html/SNPhood.html
> 
> These are the 2 vignette files with title lines:
> 
> IntroductionToSNPhood.Rmd
> title: "_SNPhood_: Investigate, quantify and visualise the epigenomic
> neighbourhood of SNPs using NGS data"
> 
> workflow.Rmd
> title: "_SNPhood_ example workflow"
> 
> It looks like the title for IntroductionToSNPhood.Rmd is being split
> across the two title entries on the landing page. Maybe this is a
> markdown formatting problem?
> 
> Thanks.
> Val

**Comment by b-long** [comment]
Other note, per Jim H.:

> [SNPhood](https://www.bioconductor.org/packages/devel/bioc/html/SNPhood.html) has two Rmarkdown vignettes titled _“SNPhood: Investigate, quantify and visualise the epigenomic neighbourhood of SNPs using NGS data”_ and _“SNPhood example workflow”_. However on the landing page the vignettes are labeled as _“quantify and visualise the epigenomic neighbourhood of SNPs using NGS data”_ and _“SNPhood: Investigate”_. Perhaps the comma or asterisks within the title are messing up the landing page generator’s parser?

**Comment by aoles** [comment]
I'm not sure this is relevant, but the SNPhood package source already
contains prebuild html files in /inst/doc. The files displayed at
http://www.bioconductor.org/packages/3.3/bioc/html/SNPhood.html are not
compiled during BioC package build.

**Comment by b-long** [comment]
Hi @aoles , thanks for the additional info!  I'm actually not sure if it's relevant, as I'm still trying to track down how the page http://www.bioconductor.org/packages/3.3/bioc/html/SNPhood.html is built.  I'll keep this issue updated as I work through it.

**Comment by b-long** [comment]
cc/ @jimhester @dtenenba 

Jim found this bit of code, which defines a function `doc_object` : https://github.com/Bioconductor/bioconductor.org/blob/a1095e3e88976a8ce0e9380ac3fa013feb09d35c/lib/helpers.rb#L270-L287

That function is called from the html: https://github.com/Bioconductor/bioconductor.org/blob/a1095e3e88976a8ce0e9380ac3fa013feb09d35c/layouts/_bioc_views_package_detail.html#L168

I'm still investigating as to why the parsing is failing.

**Comment by jimhester** [comment]
This is a confusing to me. It looks like from https://github.com/Bioconductor-mirror/biocViews/blob/386286c8399dbeeac90a143c9fc6a30a8c3a6142/R/repository.R#L436 we should already be escaping embedded commas in Vignette Titles (by using 2 commas), then at https://github.com/Bioconductor/bioconductor.org/commit/6ea3cbb567940a25074be8b0a1ee1931a5ba93fa#diff-935fb763b6715cb2837911cc8d24947eL52 we replace that with `"%%ESCAPED_COMMA%%"` when doing the splitting.

So I guess I am not sure why this was an issue in the first place, was it because the code at https://github.com/Bioconductor-mirror/biocViews/blob/386286c8399dbeeac90a143c9fc6a30a8c3a6142/R/packageDetails.R#L111-L127 is failing to take the escaped commas into account?

**Comment by dtenenba** [comment]
Yes, apparently. That code does not do anything to `pkg@htmlTitles`.

**Comment by b-long** [comment]
I'm not sure if we have unit tests for such things, but this may be a good case to start using a testing framework.

**Comment by jimhester** [comment]
Oh right this only happens with Rmarkdown vignettes outputting to HTML. So the real issue here is that https://github.com/Bioconductor-mirror/biocViews/blob/386286c8399dbeeac90a143c9fc6a30a8c3a6142/R/repository.R#L686-L710 does not escape `,` as `,,`.

Maybe we should revert https://github.com/Bioconductor/bioconductor.org/commit/6ea3cbb567940a25074be8b0a1ee1931a5ba93fa and have `getHTMLTitles()` escape the titles the same way as `getVignetteTitles()` does.

**Comment by jimhester** [comment]
And as @b-long suggests a test for both instances would be useful in https://github.com/Bioconductor-mirror/biocViews/tree/master/inst/unitTests maybe?

**Comment by jimhester** [comment]
I think the fix for this may have broken other packages, https://stat.ethz.ch/pipermail/bioc-devel/2015-October/008185.html

**Comment by dtenenba** [comment]
@jimhester lol
will fix

**Comment by b-long** [comment]
^ Definitely time for more automated tests :smiley:

**Comment by dtenenba** [comment]
I reverted the commit I made to the ruby code. @jimhester is correct that the fix belongs in biocViews. I have made the change there. The correctly formatted landing page for SNPhood will propagate later today. Jim and @b-long are correct that there should be a unit test here. That will not happen today.
