### ISSUE TITLE
Backup and Restore instructions for Solr

### ISSUE THREAD

**Issue by b-long** [Bioconductor/bioconductor.org_archive#19]
Create backup / restore procedures for Solr as a part of testing changes to the search configuration ( #15 ).

**Comment by b-long** [comment]
Initial state before restoration : 
![beforerestore](https://cloud.githubusercontent.com/assets/66993/12596199/d240d3f8-c44c-11e5-82ff-9890e87066c5.png)

State after restoration : 

![afterrestore](https://cloud.githubusercontent.com/assets/66993/12596219/e3768a14-c44c-11e5-8792-cb80619b089f.png)

**Comment by b-long** [comment]
FYI : Documentation can be viewed online: https://github.com/Bioconductor/bioconductor.org/blob/master/documentation/SolrBackupAndRestore.md 

cc/ @mtmorgan @vobencha @dtenenba

**Comment by dtenenba** [comment]
Nice. Thanks.

**Comment by Himanshusoni9** [comment]
One More issue : On  Solr Collection Data Backup Based on Condition/Data Filter.(There is no provision for that . )

Because SOLR BACKUP API with Query is not working
//http://localhost:8983/solr/admin/collections?action=RESTORE&name=myBackupName&location=C:\Users\DELL\Downloads\SOLR_BACKUP&collection=myCondCollection&query=text:cellphone

I am trying out to perform backups of our Solr data with a particular condition in mind.

To provide some context, let's say Solr collection consists of 100 records, among which 70 records contain the text "mobile," and the remaining 30 records contain the text "cellphone." my objective is to take a Solr collection/data backup that contains only the records the text "cellphone" – essentially, we want to create a backup file that reflects these 30 specific records only.

I would greatly appreciate it if you could share insights on the best practices or methods to achieve this selective backup based on a condition. If there are specific parameters or commands we should be utilizing, kindly provide the necessary guidance. Additionally, any documentation or references you could point us to would be immensely helpful.

Thank you in advance for your time and assistance. We value your expertise and look forward to implementing an efficient solution based on your recommendations.

**Comment by hpages** [comment]
I don't think you've posted to the right place here.
1. This is the bioconductor.org_archive repo. Even though we were interested in using Solr at some point, we have nothing to do with the Solr project.
2. This repo is no longer active.
3. This issue was closed more than 7 years ago.
